export default {
  PKG_HEAD: 'PACKAGE_HEAD',
  PKG_BODY: 'PACKAGE_BODY',
  FUNCTION: 'FUNCTION',
  PROCEDURE: 'PROCEDURE',
  TRIGGER: 'TRIGGER',
  SYNONYM: 'SYNONYM',
  TYPE: 'TYPE',
};

export enum PLType {
  PKG_HEAD = 'PACKAGE_HEAD',
  PKG_BODY = 'PACKAGE_BODY',
  PACKAGE_ROOT = 'PACKAGE_ROOT',
  FUNCTION = 'FUNCTION',
  PROCEDURE = 'PROCEDURE',
  TRIGGER = 'TRIGGER',
  SYNONYM = 'SYNONYM',
  TYPE = 'TYPE',
  ANONYMOUSBLOCK = 'ANONYMOUS_BLOCK',
}
