export enum AIQuestionType {
  SQL_OPTIMIZER = 'SQL_OPTIMIZER',
  SQL_DEBUGGING = 'SQL_DEBUGGING',
  NL_2_SQL = 'NL_2_SQL',
  SQL_MODIFIER = 'SQL_MODIFIER',
  SQL_FORMATTING = 'SQL_FORMATTING',
  SQL_COMPLETION = 'SQL_COMPLETION',
}
